name: "Mirror"

on:
  schedule:
    - cron:  '0 20 * * *'

jobs:
  run:
    name: Mirror
    runs-on: ubuntu-latest
    steps:
    - name: Pull CP Editor
      run: |
        git clone https://github.com/cpeditor/cpeditor
    - name: Push CP Editor
      run: |
        cd cpeditor
        git remote add gitee "https://ouuan:${{ secrets.GITEE_TOKEN }}@gitee.com/ouuan/cpeditor.git"
        git push --all -f gitee
