name: "Mirror"

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 21 * * *'

jobs:
  run:
    name: Mirror
    runs-on: ubuntu-latest
    steps:
    - name: Sleep
      run: sleep $((RANDOM / 10))
    - name: Manually mirror
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 10
        command: |
          mirror() {
            git clone "https://github.com/$1/$2"
            cd "$2"
            git remote add gitee "https://ouuan:${{ secrets.GITEE_TOKEN }}@gitee.com/ouuan/$2.git"
            git remote set-head origin -d
            git push gitee --prune +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
            cd ..
          }
          mirror MikeMirzayanov testlib
          mirror itay-grudev SingleApplication
    - name: Get Repo List
      id: list
      uses: yi-Xu-0100/repo-list-generator@v1.1.1
      with:
        allow_archived: false
        block_list: ".github"
    - name: Mirror ouuan
      uses: Yikun/hub-mirror-action@ad15ed46acd9c0a753e6fee7e85316aaab24bba5
      with:
        src: github/ouuan
        dst: gitee/ouuan
        dst_key: ${{ secrets.SSH_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        force_update: true
        debug: true
        static_list: ${{ steps.list.outputs.repoList }}
        mappings: "ouuan=>profile-readme"
    - name: Mirrow cpeditor
      uses: Yikun/hub-mirror-action@ad15ed46acd9c0a753e6fee7e85316aaab24bba5
      with:
        src: github/cpeditor
        dst: gitee/ouuan
        src_account_type: org
        dst_key: ${{ secrets.SSH_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        force_update: true
        debug: true
        black_list: ".github"
