name: "Mirror"

on:
  schedule:
    - cron:  '0 20 * * *'

jobs:
  run:
    name: Mirror
    runs-on: ubuntu-latest
    steps:
    - name: Pull CP Editor
      run: |
        git clone https://github.com/cpeditor/cpeditor --mirror
    - name: Push CP Editor
      run: |
        cd cpeditor.git
        git remote add gitee "https://ouuan:${{ secrets.GITEE_TOKEN }}@gitee.com/ouuan/cpeditor.git"
        git push --mirror gitee
    - name: Mirror ouuan
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/ouuan
        dst: gitee/ouuan
        dst_key: ${{ secrets.SSH_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        black_list: "cpeditor"
