name: "Mirror"

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 20 * * *'

jobs:
  run:
    name: Mirror
    runs-on: ubuntu-latest
    steps:
    - name: Manually mirror
      run: |
        mirror() {
          git clone "https://github.com/$1/$2"
          cd "$2"
          git remote add gitee "https://ouuan:${{ secrets.GITEE_TOKEN }}@gitee.com/ouuan/$2.git"
          git remote set-head origin -d
          git push gitee --prune +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
          cd ..
        }
        mirror cpeditor cpeditor
        mirror cpeditor QCodeEditor
        mirror cpeditor QtFindReplaceDialog
        mirror cpeditor lsp-cpp
        mirror cpeditor cpeditor.github.io
        mirror cpeditor docsy
        mirror cpeditor qhttp
        mirror cpeditor FakeVim
        mirror MikeMirzayanov testlib
        mirror itay-grudev SingleApplication
    - name: Mirror ouuan
      uses: Yikun/hub-mirror-action@v0.12
      with:
        src: github/ouuan
        dst: gitee/ouuan
        dst_key: ${{ secrets.SSH_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        force_update: true
        debug: true
        black_list: "ouuan,.github,cpeditor,QCodeEditor,QtFindReplaceDialog,lsp-cpp,cpeditor.github.io,docsy,qhttp,FakeVim,testlib,SingleApplication"
