name: "Mirror"

on: push
  # schedule:
  #   - cron:  '0 20 * * *'

jobs:
  run:
    name: Mirror
    runs-on: ubuntu-latest
    steps:
    - name: Pull CP Editor
      run: |
        git clone https://github.com/cpeditor/cpeditor
    - name: Push CP Editor
      run: |
        cd cpeditor
        git push --all "https://${GITHUB_ACTOR}:${{ secrets.GITEE_TOKEN }}@gitee.com/ouuan/cpeditor.git"
    - name: Mirror ouuan
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/ouuan
        dst: gitee/ouuan
        dst_key: ${{ secrets.SSH_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
